spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characyerEncoding=utf-8
    data-username: root
    data-password: 980404
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    zyy.show.blog: info
  file:
    path: log/blog-pro.log

